name: fexr
description: RPC SDK for Fexr.
repository: https://github.com/getfexr/fexr-flutter
issue_tracker: https://github.com/getfexr/fexr-flutter/issues
version: 0.7.7

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">1.20.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.2
  protobuf: ^2.1.0
  path_provider: ^2.0.8
  image: ^3.2.0
  sha3: ^0.2.0
  convert: ^3.0.2
  fixnum: ^1.0.1
  
  # run on terminal before generating proto: dart pub global activate protoc_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.1.0

flutter:

  assets:
    - lib/utils/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:
 # plugin:
  #  platforms:
   #   android:
    #    package: fexr
     #   pluginClass: Fexr
      #ios:
       # pluginClass: Fexr
      #macos:
       # pluginClass: Fexr
      # windows:
      #   pluginClass: Fexr
      # linux:
      #   pluginClass: Fexr
      # ios:
      #   pluginClass: Fexr
      # macos:
      #   pluginClass: HelloPlugin
      # web:
      #   pluginClass: HelloPlugin
      #   fileName: hello_web.dart

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
